### ISSUE TITLE
Just having question.

### ISSUE THREAD

**Issue by KubaTMofficial** [gd-programming/gddocs#54]
I found in data folder in server database this level data and I have question how is it encoded? I'm asking it here because Discord link in documentation doesnt work. Code:

**Comment by Jecket22** [comment]
It's not secretly encoded or anything, it's just how the game interprets level data into objects

**Comment by SMJSGaming** [comment]
The encoding is Base64, XOR and then GZIP
However be careful with sharing files like these and make sure to block access to the data  folder using a .htaccess file with the following content:
```text
order deny,allow
deny from all
```
because of the fact that certain types of save files contain private data about the user like login details.

**Comment by SMJSGaming** [comment]
Eh, if those devs would need this info I genuinely question if they're capable of making their own GDPS. This is some really basic stuff compared to some other features in a GD server.
